### PR TITLE
extract `thread_id` from relation status in relation cancel

### LINKED ISSUE #23: Relationship cancellation messages are sent with the wrong `thread_id`

### PR DESCRIPTION
**Pull request by folkertdev**
fixes #23

### CODE REVIEW

File: tsp/src/store.rs [hunk 1]
```diff
@@ -732,9 +745,15 @@ impl Store {
...
-        let thread_id = Default::default(); // FNORD
+        let old_relationship =
+            self.replace_relation_status_for_vid(receiver, RelationshipStatus::Unrelated)?;
+
+        let thread_id = match old_relationship {
+            RelationshipStatus::_Controlled => todo!(),
+            RelationshipStatus::Bidirectional { thread_id, .. } => thread_id,
+            RelationshipStatus::Unidirectional { thread_id } => thread_id,
+            RelationshipStatus::Unrelated => todo!(),
+        };
```
Comment (folkertdev) [inline tsp/src/store.rs:756]: so, what should the other branches do here? also are the bidirectional `outstanding_nested_thread_ids` relevant here?

Comment (squell) [reply tsp/src/store.rs:756]: `Unrelated` and `_Controlled` -> there is no relationship to cancel, so return an Error like `Error::Relationship`. 

The `outstanding_nested_thread_ids` are unrelated here. Although this does raise the question of what it means if someone tries to request a new nested relationship, then cancels the parent relationship.

**Review by squell — CHANGES_REQUESTED** [review]
The `todo!`'s in `make_relationship_cancel` should be `return Error::...`. Other than that looks good to me
